apiVersion: apps/v1
kind: Deployment
metadata:
  name: cron
  labels:
    app: cron
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cron
  template:
    metadata:
      labels:
        app: cron
    spec:
      containers:
      - name: cron
        image: gcr.io/cron-224817/cron@sha256:d7bdcfb4e838c1c79f4ed84648133189a8353316fdb62ae66c58c9c744fde73b
        ports:
        - containerPort: 3000