apiVersion: apps/v1
kind: Deployment
metadata:
  name: cron
  labels:
    app: cron
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cron
  template:
    metadata:
      labels:
        app: cron
    spec:
      containers:
      - name: cron
        image: gcr.io/cron-224817/cron@sha256:1810ebc1b0df489808b1d2b108cab25cbee24239c5439be619030f03f81674c1
        ports:
        - containerPort: 3000