apiVersion: apps/v1
kind: Deployment
metadata:
  name: cron
  labels:
    app: cron
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cron
  template:
    metadata:
      labels:
        app: cron
    spec:
      containers:
      - name: cron
        image: gcr.io/cron-224817/cron@sha256:9c0a41f92e3a48c58fd666d15c174f25236b9074de8129693c27617ad1acdf0f
        ports:
        - containerPort: 3000