apiVersion: apps/v1
kind: Deployment
metadata:
  name: cron
  labels:
    app: cron
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cron
  template:
    metadata:
      labels:
        app: cron
    spec:
      containers:
      - name: cron
        image: gcr.io/cron-224817/cron@sha256:9bdaedc0be70a398078fa26a38ded37a0361eaedbc03f85d10289d1fda4a9bff
        ports:
        - containerPort: 3000