apiVersion: v1
kind: PersistentVolume
metadata:
  name: cron-storage
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: disk-1
    fsType: ext4
