apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yaml: |
    global:
      scrape_interval: 30m
      scrape_timeout: 10s
      evaluation_interval: 30m
    scrape_configs:
        - job_name: cron
          metrics_path: /metrics
          scheme: http
          static_configs:
            - targets:
              - cron-svc
