apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
        - name: prometheus
          image: gcr.io/cloud-marketplace/google/prometheus@sha256:f8d1d865b322be20ee34ca3ee61b012bcdbe8235ee57bc7596b6b63d33a90d8c
          command: [ "prometheus", "--config.file=/config/prometheus.yaml", "--storage.tsdb.retention=1y" ]
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /config
            - name: data-volume
              mountPath: /prometheus
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus-config
        - name: data-volume
          persistentVolumeClaim:
            claimName: cron-storage-claim