global:
  scrape_interval: 5m
  scrape_timeout: 10s
  evaluation_interval: 5m
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
scrape_configs:
- job_name: cron
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - cron-svc